import "./globals.css";
import { Inter } from "next/font/google";

import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>
        <Header />
      </header>
      <body className={inter.className}>{children}</body>
      <footer>this is a footer</footer>
    </html>
  );
}
