import { NextIntlClientProvider, useMessages } from 'next-intl';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { unstable_setRequestLocale } from 'next-intl/server';
import useTextDirection from '@/hooks/useTextDirection';
import '@/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = useMessages();
  const dir = useTextDirection();

  return (
    <html lang={locale} dir={dir}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
