#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Run ESLint with automatic fixes, and capture the result and exit code
eslint_result=$(npx eslint . --fix)
eslint_exit_code=$?
if [ $eslint_exit_code -eq 0 ]; then
    printf "✅ ESLint checks passed!\n"
else
    printf "❌ ESLint found issues that could not be automatically fixed.\n%s\n" "$eslint_result"
    exit 1
fi

# Run Prettier with write option, capture the result and exit code
prettier_result=$(npx prettier --write .)
prettier_exit_code=$?
if [ $prettier_exit_code -eq 0 ]; then
    printf "✅ Prettier formatting passed!\n"
else
    printf "❌ Prettier found formatting issues.\n%s\n" "$prettier_result"
    exit 1
fi

printf "✨ All checks passed! Your code is clean and formatted! ✨\n"
